### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by DGojka** [DGojka/ReadingStats#39]
```
Refactor code with viewbining and dagger extensions, and make it easier to read and more clean.
Make sure everything complies with the MVVM architecture.
```
- [x] Main screen - #30  
- [x] Book details fragment - #35 
- [ ] Realtime sessions - #36 
- [x] Book creation cleanup - #31
- [ ] Change book creation algorithm - #34 

`Also fix those critical bugs: `
- [ ] #37 
- [ ] #33
